version: '3'

services:
  backend:
    container_name: "backend"
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./:/app/backend
  
  frontend:
    container_name: "frontend"
    build: ./frontend
    ports:
      - "4200:4200"
    volumes:
      - ./:/app/frontend
    restart: always
